### ISSUE TITLE
get http 500 internal server error after intallation

### ISSUE THREAD

**Issue by robot22** [fhoner/Schichtplaner#2]
Hello,
just tried to install the project but when I open the address I get http 500 internal server error.

May somebody can help me with more detailed installation steps.

Here more information about my setup and installation

VM: Ubuntu-Server  16.04.2
Apache 2.4.18, PHP7.0.15, MySQL 5.7.17
Installed nodejs, npm, composer, grunt
modified sample config
database via SQL file imported
as I put the files also in directory /planer/ I guess that there is no need to change .htaccess

maybe it's just a problem in my setup. Can somebody help. As well tipps are welcome via e-mail: mk1091@web.de

Thanks

Markus

**Comment by fhoner** [comment]
Hi Markus,
thanks for your interest in Schichtplaner. 
In order to help you please show the content of your htaccess. What is your request URL to the application (e.g. http://localhost/planer/)?

**Comment by robot22** [comment]
Hi Felix,

content of my htaccess is:
Options +FollowSymlinks
RewriteEngine On
RewriteBase /planer/

all files are stored on the webserver in: /var/www/html/planer so this should be ok

when I checked the log files I saw some error messages - see attached file
[logs.txt](https://github.com/fhoner/Schichtplaner/files/852497/logs.txt)

It looks like there are some files missing e.g. Indenter.php.
By a serach on github I found this project: https://github.com/gajus/dindent

Maybe there are some dependencies missing so that I need to install parts of this project es well?

Thanks for your support.

**Comment by fhoner** [comment]
Hi Markus,

you are right, the indent dependency caused the error. As the project does not need the indenter at all I simply removed the setting from config file.
Please redo the installation steps with the current state of the repository. There were some missing database structures as well which will cause problems otherwise.

Thanks for your interest
Felix

**Comment by robot22** [comment]
Hello Felix,

not it works as expected. Thanks for your support :)

Markus
