### ISSUE TITLE
sampledb issues

### ISSUE THREAD

**Issue by robot22** [fhoner/Schichtplaner#3]
Hello,

when I tried to create a new plan it was not working with the sampledb because default value for table planer_plan.position wasn't set. 

I'm new on GitHub and don't know how I can correct this without doublicate the files. 

Regards 
Markus

**Comment by fhoner** [comment]
Hi

I pushed my current development state in the hope it works fine now (I'm busy at the moment and don't have time for extensive testing). Notice that the admin area still got few bugs and is unprotected by default. 
Please download latest version and reimport the new database.

Felix

**Comment by robot22** [comment]
Hi Felix,

no problem at all. I just tested the project to have it as an option for the planning of time shifts in our volunteer fire brigade next time. 

I figured out several bugs in the admin portal. For example that not all necessary database entries was created when I added new shifts / production lines and that the pdf export did not work for me. 

As workaround I added all data straight to the database without the UI - this works well if I use the tool just few times a year to plan some event.

For me I also want to simplify the form for entering new names in a shift whithout having the option to enter mail address....maybe this could also be an option for the admin tool to enable or disable this feature.

Currently I do also not have time to start further develloping. So at this point I really want to thank you for your work so far and I'll keep on watching how this project is growing.

We keep in contact.

Cheers!

Markus

**Comment by fhoner** [comment]
Hey Markus,

that's the way I worked with the tool in the past to be honest. I'm gonna put work into the admin panel when I got some time for it.
I've noticed the thing with the email input, for now you can leave it blank as it is not a required field. The broken PDF export is fixed now, there was a mistake in the config.php which didn't broke the export on my local machine.

Thanks for contacting

Felix

**Comment by robot22** [comment]
Thanks for the update :)
